### ISSUE TITLE
Black (AMOLED) theme

### ISSUE THREAD

**Issue by Grammost** [kriztan/blabber.im#269]
I know Pix-Art already has a dark theme, but an additional black theme for OLED/AMOLED displays would also be nice.

**Comment by genofire** [comment]
At the moment is theming a big problem, because it was implementet (in Conversations already) in a really bad way. There are everywhere boolean handling with `if`s instatt of a (Enum) variable or theme class / with methods.

So it is a complete refactoring of the app necessary.

---

I am thinking about a solution like in https://simplemobiletools.github.io/ would be nice:

![screenshot_20181116-103301_gallery](https://user-images.githubusercontent.com/6905586/48613084-ad75d100-e982-11e8-8635-a54821934bcd.png)
![screenshot_20181116-103523_gallery](https://user-images.githubusercontent.com/6905586/48613205-00e81f00-e983-11e8-89f5-5a9716c12997.png)

**Comment by iNPUTmice** [comment]
@genofire what is a better way to implement it?

**Comment by genofire** [comment]
Good question - 
I would create three or more settings for a color:

https://github.com/SimpleMobileTools/Simple-Commons/blob/720ec6a9a71545883fab52e180a862c1eaccc50a/commons/src/main/kotlin/com/simplemobiletools/commons/activities/CustomizationActivity.kt#L161-L164

A little Utils/ Helper class `Themen`, maybe as singelton:
https://github.com/SimpleMobileTools/Simple-Commons/blob/42bc3aa75fec50fc633f3b95a6968e4e6660a79b/commons/src/main/kotlin/com/simplemobiletools/commons/models/MyTheme.kt#L3

Where i put some nice methods to adjusted those colors in different brightness scales, and so on:
https://github.com/SimpleMobileTools/Simple-Commons/blob/720ec6a9a71545883fab52e180a862c1eaccc50a/commons/src/main/kotlin/com/simplemobiletools/commons/extensions/Context.kt#L79-L89

The settings ui should also not be the problem:
https://github.com/SimpleMobileTools/Simple-Commons/blob/master/commons/src/main/kotlin/com/simplemobiletools/commons/activities/CustomizationActivity.kt

with a list of themes:
https://github.com/SimpleMobileTools/Simple-Commons/blob/720ec6a9a71545883fab52e180a862c1eaccc50a/commons/src/main/kotlin/com/simplemobiletools/commons/activities/CustomizationActivity.kt#L115-L122

and color pattern:
https://github.com/SimpleMobileTools/Simple-Commons/blob/master/commons/src/main/res/values/colors.xml
https://github.com/SimpleMobileTools/Simple-Commons/blob/master/commons/src/main/kotlin/com/simplemobiletools/commons/extensions/Activity-themes.kt



The question is only, how to get thews colors to the ui elements.
1. by extends e.g. `Activities` to `MyActivities` and `Button` to `MyButton` which read the stored settings by using the `Theme` class
2. by write every ui init on already existing class (like the dark mode on using the `Theme` class)
3. find a more intelligent way, like on Kotlin: https://github.com/SimpleMobileTools/Simple-Commons/blob/720ec6a9a71545883fab52e180a862c1eaccc50a/commons/src/main/kotlin/com/simplemobiletools/commons/extensions/Context.kt#L61-L77

**Comment by genofire** [comment]
https://github.com/MaxFour/Music-Player/tree/master/appthemehelper
It looks like the third way over changing Context should be the right way.
(Must of this `class`es exists there already: [ThemeStore.class](https://github.com/MaxFour/Music-Player/blob/master/appthemehelper/src/main/java/com/maxfour/appthemehelper/ThemeStore.java))

**Comment by streaps** [comment]
The dark theme could be improved. Some parts are a little bit too dark for my taste. How would a OLED/AMOLED theme be different?

**Comment by genofire** [comment]
every grey would be real black, so that a AMOLED display does not use thus pixel.

**Comment by subpub** [comment]
Don't you think this and other custom theme issues are a job for Integrating a third party theme engine library like 

- https://github.com/jaredrummler/Cyanea

Or
- https://github.com/pranavpandey/dynamic-support 

Both require AndroidX support.

**Comment by subpub** [comment]
After some playing around, it seems Dynamic-support's [Dynamic-theme](https://github.com/pranavpandey/dynamic-theme) dependency is much more powerful than Cyanea.

Has auto & manual day-night theme 

Has Accent color pallete

Has Background Aware and True Color options https://GitHub.com/pranavpandey/dynamic-support/issues/9

(Hidden) Support for customizing border radius , card elevation, font size, theme import https://theme.pranavpandey.com/help

**Comment by Avispa** [comment]
@genofire commented on 16 Nov 2018
> At the moment is theming a big problem, because it was implementet (in Conversations already) in a really bad way.

At the risk of being controversial but wouldn't it be more logical to fix it in *Conversations*? I know, for a "real" dev, mentally it's a pain since it's not your/ours/this project but wouldn't it be a win-win? It would even supporting the real idea of open source and forks. ;-)

> But we have to keep in mind that this is a fork from Conversations and this should be a fork. The Conversations developer makes a great job with integrating security fixes and so on and I want my messager to be compatible with these fixes.

_Originally posted by @kriztan in https://github.com/kriztan/Pix-Art-Messenger/issues/121#issuecomment-368989906_
